<div>
    <livewire:livewire-datatable
        :model="$model"
        :columns="$columns"
        :searchable="$searchable"
        :unsortable="$unsortable"
        :custom-columns="$customColumns"
        default-sort-field="name"
        default-sort-direction="asc"
    />
</div>
