<?php

namespace App\Filament\Marketing\Resources\AdCampaigns\Actions;

use App\Enums\CampaignStatus;
use App\Models\AdCampaign;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Illuminate\Support\Facades\Log;

class ApproveCampaignAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this
            ->label('Approve Campaign')
            ->color('success')
            ->icon('heroicon-o-check-circle')
            ->requiresConfirmation()
            ->modalHeading('Approve Campaign')
            ->modalDescription('Are you sure you want to approve this campaign? This will make it active.')
            ->modalSubmitActionLabel('Yes, Approve Campaign')
            ->visible(fn (?AdCampaign $record): bool => auth()->user()->isAdmin() && $record && $record->status === CampaignStatus::PendingReview)
            ->action(function (AdCampaign $record): void {
                try {
                    $record->updateOrFail([
                        'status' => CampaignStatus::Active,
                        'reviewed_by' => auth()->user()->id,
                        'reviewed_at' => now(),
                    ]);
                    Notification::make()
                        ->title('Campaign Approved')
                        ->body('Campaign has been approved successfully.')
                        ->success()
                        ->send();
                } catch (\Exception $e) {
                    Log::error('Error Approving Campaign', ['campaign_id' => $record->id, 'error' => $e->getMessage()]);

                    Notification::make()
                        ->title('Campaign Approval Failed')
                        ->body($e->getMessage())
                        ->danger()
                        ->send();

                    throw $e;
                }
            });
    }
}
