<?php

namespace App\Filament\Marketing\Resources\AdCampaigns\Actions;

use App\Enums\CampaignStatus;
use App\Models\AdCampaign;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Facades\Log;

class CompleteCampaignAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this
            ->label('Mark Complete')
            ->color('info')
            ->icon(Heroicon::OutlinedCheckBadge)
            ->requiresConfirmation()
            ->modalHeading('Mark Campaign as Complete')
            ->modalDescription('Are you sure you want to complete this campaign? This will stop the campaign from running.')
            ->modalSubmitActionLabel('Yes, Complete Campaign')
            ->visible(fn (?AdCampaign $record): bool => $record && in_array($record->status, [CampaignStatus::Active, CampaignStatus::Paused, CampaignStatus::Exhausted]))
            ->action(function (AdCampaign $record): void {
                try {
                    $record->updateOrFail([
                        'status' => CampaignStatus::Completed,
                    ]);
                    Notification::make()
                        ->title('Campaign Marked Completed')
                        ->body('Campaign has been marked completed successfully.')
                        ->success()
                        ->send();
                } catch (\Exception $e) {
                    Log::error('Error Marking Campaign Completed', ['campaign_id' => $record->id, 'error' => $e->getMessage()]);

                    Notification::make()
                        ->title('Campaign Complete Failed')
                        ->body($e->getMessage())
                        ->danger()
                        ->send();

                    throw $e;
                }
            });
    }
}
