<?php

namespace App\Filament\Marketing\Resources\AdCampaigns\Actions;

use App\Enums\CampaignStatus;
use App\Models\AdCampaign;
use Filament\Actions\Action;
use Filament\Notifications\Notification;
use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Facades\Log;

class PauseCampaignAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this
            ->label('Pause Campaign')
            ->color('warning')
            ->icon(Heroicon::OutlinedPause)
            ->requiresConfirmation()
            ->modalHeading('Pause Campaign')
            ->modalDescription('Are you sure you want to pause this campaign? This will stop the campaign from running.')
            ->modalSubmitActionLabel('Yes, Pause Campaign')
            ->visible(fn (?AdCampaign $record): bool => $record && $record->status === CampaignStatus::Active)
            ->action(function (AdCampaign $record): void {
                try {
                    $record->updateOrFail([
                        'status' => CampaignStatus::Paused,
                    ]);
                    Notification::make()
                        ->title('Campaign Paused')
                        ->body('Campaign has been submitted successfully.')
                        ->success()
                        ->send();
                } catch (\Exception $e) {
                    Log::error('Error Submitting Campaign', ['campaign_id' => $record->id, 'error' => $e->getMessage()]);

                    Notification::make()
                        ->title('Campaign Submit Failed')
                        ->body($e->getMessage())
                        ->danger()
                        ->send();

                    throw $e;
                }
            });
    }
}
