<?php

namespace App\Filament\Marketing\Resources\AdCampaigns\Actions;

use App\Enums\CampaignStatus;
use App\Models\AdCampaign;
use Filament\Actions\Action;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Notifications\Notification;
use Filament\Schemas\Components\Section;
use Filament\Support\Icons\Heroicon;
use Illuminate\Support\Facades\Log;

class RejectCampaignAction extends Action
{
    public static function make(?string $name = null): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this
            ->label('Reject Campaign')
            ->color('danger')
            ->icon(Heroicon::OutlinedExclamationTriangle)
            ->requiresConfirmation()
            ->modalHeading('Reject Campaign')
            ->modalDescription('Are you sure you want to reject this campaign? This will stop the campaign from running.')
            ->modalSubmitActionLabel('Yes, Reject Campaign')
            ->visible(fn (?AdCampaign $record): bool => auth()->user()->isAdmin() && $record && in_array($record->status, [CampaignStatus::PendingReview, CampaignStatus::Exhausted, CampaignStatus::Active]))
            ->schema([
                Section::make()->schema([
                    MarkdownEditor::make('rejection_reason')
                        ->label('Reason for Rejection')
                        ->required(),
                ]),
            ])
            ->action(function (array $data, AdCampaign $record): void {
                try {
                    $record->updateOrFail([
                        'status' => CampaignStatus::Rejected,
                        'reviewed_by' => auth()->user()->id,
                        'reviewed_at' => now(),
                        'rejected_reason' => $data['rejection_reason'],
                    ]);
                    Notification::make()
                        ->title('Campaign Paused')
                        ->body('Campaign has been submitted successfully.')
                        ->success()
                        ->send();
                } catch (\Exception $e) {
                    Log::error('Error Submitting Campaign', ['campaign_id' => $record->id, 'error' => $e->getMessage()]);

                    Notification::make()
                        ->title('Campaign Submit Failed')
                        ->body($e->getMessage())
                        ->danger()
                        ->send();

                    throw $e;
                }
            });
    }
}
